apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - frontend
      containers:
        - name: frontend
          image: 010438506754.dkr.ecr.us-east-1.amazonaws.com/test/frontend:20241024-1159
          imagePullPolicy: Always 
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"  
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
